### ISSUE TITLE
Please add a @Pipe/@Directive/@Component annotation.

### ISSUE THREAD

**Issue by nbijl** [Tsmith18256/ng2-inline-href#6] opened 2017-06-01 07:30 UTC
If got this error when building the project like this: 
ng build --env=prod --prod --aot=true

> ERROR in Unexpected value 'InlineHrefDirective in /Users/nbijl/projects/nomad-app/node_modules/ng-inline-href/inline-href.d.ts' declared by the module 'ComponentsModule in /Users/nbijl/projects/nomad-app/src/app/components/components.module.ts'. Please add a @Pipe/@Directive/@Component annotation.

Our package.json dependencies:
```json
"dependencies": {
        "@angular/animations": "^4.1.3",
        "@angular/common": "^4.1.3",
        "@angular/compiler": "^4.1.3",
        "@angular/core": "^4.1.3",
        "@angular/forms": "^4.1.3",
        "@angular/http": "^4.1.3",
        "@angular/platform-browser": "^4.1.3",
        "@angular/platform-browser-dynamic": "^4.1.3",
        "@angular/router": "^4.1.3",
        "angular-2-local-storage": "^1.0.1",
        "angular2-jwt": "^0.2.3",
        "angular2-moment": "^1.3.3",
        "core-js": "^2.4.1",
        "markdown-to-html-pipe": "^1.2.1",
        "ng-inline-href": "^2.0.4",
        "ng2-translate": "^5.0.0",
        "ngx-bootstrap": "^1.6.6",
        "ngx-clipboard": "^8.0.2",
        "rxjs": "^5.4.0",
        "web-animations-js": "^2.2.5",
        "zone.js": "^0.8.11"
    }
```

Any ideas?

**Comment by Tsmith18256** [comment] 2017-06-01 17:28
Hey @nbijl, I can take a look at this for you and see if I can figure out what's going on, but I will need access to a project that suffers from the error so that I can reproduce it.

**Comment by georgdonner** [comment] 2017-06-04 19:11
Hey @Tsmith18256, I've encountered the same issue in my project and created a new application with the CLI. Seems like that one suffers from the same issue, so you should be able to reproduce executing `ng build --prod`! You can find it [here](https://github.com/LinkinGeorge/inline-href).

That's what I get when running `ng -v`: 

    @angular/cli: 1.0.0
    node: 6.10.2
    os: win32 x64
    @angular/common: 4.1.3
    @angular/compiler: 4.1.3
    @angular/core: 4.1.3
    @angular/forms: 4.1.3
    @angular/http: 4.1.3
    @angular/platform-browser: 4.1.3
    @angular/platform-browser-dynamic: 4.1.3
    @angular/router: 4.1.3
    @angular/cli: 1.0.0
    @angular/compiler-cli: 4.1.3

And that's the error showing up: 
![screenshot_122](https://cloud.githubusercontent.com/assets/15929116/26764619/eb29d702-4961-11e7-87e9-231c504a93ec.png)

**Comment by Tsmith18256** [comment] 2017-06-05 17:45
Thanks for the demo @LinkinGeorge, I should get a chance to look at this tonight!

**Comment by Tsmith18256** [comment] 2017-06-06 05:00
Hey guys, I've been looking into this but haven't been able to trace a cause. Looks like we aren't the only ones seeing this since Angular 4.

https://github.com/angular/angular/issues/15890
https://github.com/angular/angular/issues/15763

I'm going to keep investigating to see if I can get anything to work. In the meantime, let me know if either of you figure something out, and hopefully something new develops in the Angular repo.

**Comment by Tsmith18256** [comment] 2017-06-06 05:07
Ha! Got it! Disregard that last comment haha. Updated version coming in soon! 😄

**Comment by Tsmith18256** [comment] 2017-06-06 05:49
The repro project builds fine with`ng build --prod` using the latest version of _ng-inline-href_ on NPM (v2.0.5). I am closing this issue, please let me know if either of you still experience the error after updating to 2.0.5.

**Comment by nbijl-worthit** [comment] 2017-06-06 07:26
Is this related to : https://github.com/angular/angular-cli/issues/6557 ?

**Comment by georgdonner** [comment] 2017-06-06 08:53
Hey there, so the `ng build --prod` builds fine in both my private and the repro project, however, the directive doesn't work if I built it with the production flag. Without the production flag it's still working fine...
I noticed that the directive seems to generate `href="http://localhost:4200/undefined"` for the `<use>` tag.
I've updated the repro project to 2.0.5 and ran `ng serve --prod`, I hope you can reproduce :)

**Comment by Tsmith18256** [comment] 2017-06-06 17:12
Hey @nbijl-worthit, this didn't end up being related to Angular. The issue was that the typings declarations file that I was generating with `tsc --declarations <file>` wasn't including the `@Directive` decorator. The decorator metadata was in the .js file, but the original decorator needed to be in the .d.ts file.

@LinkinGeorge Damn, okay thanks... I've opened a new issue related to that one. (#8)

**Comment by sviklim** [comment] 2017-09-06 21:45
Hi! I'm sorry, but it looks like `2.1.1` release has brought this issue back. Here is a part of the log I got executing `ng build --prod`:

> ```error	06-Sep-2017 21:06:30	ERROR in Unexpected value 'InlineHrefDirective in /opt/bamboo/bamboo-home/xml-data/build-dir/GAME-GAWT319-JOB1/node_modules/ng-inline-href/inline-href.d.ts' declared by the module 'SharedModule in /opt/bamboo/bamboo-home/xml-data/build-dir/GAME-GAWT319-JOB1/src/app/shared/shared.module.ts'. Please add a @Pipe/@Directive/@Component annotation.```

**Comment by Tsmith18256** [comment] 2017-09-09 17:34
Ugh, I gotta figure out why TypeScript isn't emitting these in the declarations file. Thanks for pointing this out @sviklim, I'm fixing it right now.

**Comment by Tsmith18256** [comment] 2017-09-11 02:01
I have rolled out a patch for this that also addresses the underlying issue that was causing this in the first place. Please update to 2.1.2 and this issue should not happen again.

**Closed as completed by Tsmith18256** 2017-09-11 02:01 UTC
